smart-home:
  device-map:
    kitchen:
      light:
        id: 12
        esp: esp0
        pin: 12
      fan:
        id: 13
        esp: esp0
        pin: 13
    myroom:
      light:
        id: 12
        esp: esp0
        pin: 12
      fan:
        id: 13
        esp: esp0
        pin: 13
com:
  crisper:
    voice: AI
    chatbot: AI

spring.datasource.url: jdbc:h2:mem:testdb
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: sa
springspring.datasource.password:
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
server.port: 8080

app.voice.url: D:\\projetcs\\server\\server\\src\\main\\resources\\T2S.py
app.bot.url: D:\\projetcs\\server\\server\\src\\main\\resources\\botResource
app.python.version: python
# Logging

logging.level.root: INFO
