spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
springspring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialectlogging.level.root=INFO

com.amazon.ask.servlet.disableRequestSignatureCheck=true
com.amazon.speech.speechlet.servlet.timestampTolerance=3600000
#javax.net.ssl.keyStore=YOUR-KEYSTORE-FILE-PATH-HERE
#javax.net.ssl.keyStorePassword=YOUR-KEYSTOREPASSWORD-HERE